services:
    frontend-app:
        image: neurochar-frontend-client-frontend-room:v1
        restart: unless-stopped
        ports:
            - 127.0.0.1:3010:3000
        logging:
            driver: json-file
            options:
                max-size: "50m"
                max-file: "5" 
        environment:
            NUXT_PUBLIC_API_BASE: https://api.neurochar.ru